/**
 * Mock 사용자 프로필 데이터
 *
 * 순환 참조 방지를 위해 별도 파일로 분리됨
 * - mock-data.ts에서 MOCK_USERS 생성에 사용
 * - follow-context.tsx에서 팔로우 기능에 사용
 */

import type { UserProfile } from "@/types/follow";

export const MOCK_USER_PROFILES: UserProfile[] = [
    {
        id: "user1",
        nickname: "페스티벌러",
        avatar: "🎵",
        bio: "공연 다니는 게 인생 낙! 록 페스티벌 광팬입니다.",
        followerCount: 42,
        followingCount: 28,
        attendedCount: 15,
        joinedAt: new Date("2024-01-15"),
        featuredBadges: ["concert_fan", "festival_lover"],
    },
    {
        id: "user2",
        nickname: "록페스러버",
        avatar: "🎸",
        bio: "지산, 펜타포트 매년 갑니다!",
        followerCount: 156,
        followingCount: 89,
        attendedCount: 48,
        joinedAt: new Date("2023-06-20"),
        featuredBadges: ["festival_master", "nationwide_tourer"],
    },
    {
        id: "user3",
        nickname: "인디키드",
        avatar: "🎤",
        bio: "홍대 인디씬 탐험 중",
        followerCount: 73,
        followingCount: 41,
        attendedCount: 32,
        joinedAt: new Date("2023-11-05"),
        featuredBadges: ["concert_fan", "seoul_conqueror"],
    },
    {
        id: "user4",
        nickname: "투어러",
        avatar: "🚀",
        bio: "전국 콘서트 투어러! 어디든 갑니다",
        followerCount: 234,
        followingCount: 112,
        attendedCount: 67,
        joinedAt: new Date("2023-03-10"),
        featuredBadges: ["nationwide_tourer", "performance_god"],
    },
    {
        id: "user5",
        nickname: "재즈매니아",
        avatar: "🎷",
        bio: "재즈 클럽 투어 중",
        followerCount: 45,
        followingCount: 33,
        attendedCount: 28,
        joinedAt: new Date("2024-02-01"),
    },
    {
        id: "user6",
        nickname: "DJ마스터",
        avatar: "🔥",
        bio: "EDM is my life",
        followerCount: 189,
        followingCount: 76,
        attendedCount: 41,
        joinedAt: new Date("2023-08-15"),
    },
    // 대규모 크루 테스트용 추가 사용자 (user7~user12)
    {
        id: "user7",
        nickname: "기타치는곰",
        avatar: "🐻",
        bio: "기타 하나로 세상을 여행해요",
        followerCount: 28,
        followingCount: 15,
        attendedCount: 12,
        joinedAt: new Date("2024-05-10"),
    },
    {
        id: "user8",
        nickname: "드러머킴",
        avatar: "🥁",
        bio: "비트가 곧 인생",
        followerCount: 56,
        followingCount: 34,
        attendedCount: 22,
        joinedAt: new Date("2024-06-15"),
    },
    {
        id: "user9",
        nickname: "베이시스트",
        avatar: "🎸",
        bio: "저음의 매력에 빠진 사람",
        followerCount: 31,
        followingCount: 22,
        attendedCount: 18,
        joinedAt: new Date("2024-07-01"),
    },
    {
        id: "user10",
        nickname: "보컬리스트",
        avatar: "🎤",
        bio: "노래하며 살아요",
        followerCount: 89,
        followingCount: 45,
        attendedCount: 30,
        joinedAt: new Date("2024-07-15"),
    },
    {
        id: "user11",
        nickname: "키보디스트",
        avatar: "🎹",
        bio: "건반 위의 마법사",
        followerCount: 42,
        followingCount: 28,
        attendedCount: 15,
        joinedAt: new Date("2024-08-01"),
    },
    {
        id: "user12",
        nickname: "퍼커셔니스트",
        avatar: "🪘",
        bio: "리듬이 곧 나",
        followerCount: 25,
        followingCount: 19,
        attendedCount: 10,
        joinedAt: new Date("2024-08-15"),
    },
];
